import { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'

import axios from 'axios'
import StartingPage from '../components/functionalComponents/MainScreen'




export const Home: NextPage = () => {
  
 
  return (
    <>
      <Head>
        <title>Brainwiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/brain-2029391.svg" />
      </Head>
      <StartingPage />
    </>
  )
}






export default Home;



